from datetime import datetime, timezone

from .models import CitizenReport, ReportCategory, ReportStatus


POLITICIANS = [
    {
        "id": 1,
        "name": "Narendra Modi",
        "constituency": "Varanasi",
        "state": "Uttar Pradesh",
        "party": "BJP",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Shri_Narendra_Modi_%28cropped%29.jpg/200px-Shri_Narendra_Modi_%28cropped%29.jpg",
        "total_promises": 25,
        "promises_kept": 18,
        "promises_broken": 4,
        "promises_in_progress": 3,
        "fulfillment_rate": 72.0,
    },
    {
        "id": 2,
        "name": "Rahul Gandhi",
        "constituency": "Wayanad",
        "state": "Kerala",
        "party": "INC",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Rahul_Gandhi_%28crop%29.jpg/200px-Rahul_Gandhi_%28crop%29.jpg",
        "total_promises": 18,
        "promises_kept": 9,
        "promises_broken": 5,
        "promises_in_progress": 4,
        "fulfillment_rate": 50.0,
    },
    {
        "id": 3,
        "name": "Arvind Kejriwal",
        "constituency": "New Delhi",
        "state": "Delhi",
        "party": "AAP",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Arvind_Kejriwal_%28cropped%29.jpg/200px-Arvind_Kejriwal_%28cropped%29.jpg",
        "total_promises": 30,
        "promises_kept": 24,
        "promises_broken": 3,
        "promises_in_progress": 3,
        "fulfillment_rate": 80.0,
    },
    {
        "id": 4,
        "name": "Mamata Banerjee",
        "constituency": "Bhowanipore",
        "state": "West Bengal",
        "party": "TMC",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Mamata_Banerjee_-_Kolkata_2012-01-28_9699.JPG/200px-Mamata_Banerjee_-_Kolkata_2012-01-28_9699.JPG",
        "total_promises": 20,
        "promises_kept": 12,
        "promises_broken": 5,
        "promises_in_progress": 3,
        "fulfillment_rate": 60.0,
    },
    {
        "id": 5,
        "name": "Amit Shah",
        "constituency": "Gandhinagar",
        "state": "Gujarat",
        "party": "BJP",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Amit_Shah_2024_%28cropped%29.jpg/200px-Amit_Shah_2024_%28cropped%29.jpg",
        "total_promises": 15,
        "promises_kept": 11,
        "promises_broken": 2,
        "promises_in_progress": 2,
        "fulfillment_rate": 73.3,
    },
    {
        "id": 6,
        "name": "Akhilesh Yadav",
        "constituency": "Azamgarh",
        "state": "Uttar Pradesh",
        "party": "SP",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Akhilesh_Yadav_in_2022_%28cropped%29.jpg/200px-Akhilesh_Yadav_in_2022_%28cropped%29.jpg",
        "total_promises": 22,
        "promises_kept": 10,
        "promises_broken": 8,
        "promises_in_progress": 4,
        "fulfillment_rate": 45.5,
    },
]


REPORTS = [
    CitizenReport(
        id=1,
        politician_id=1,
        area="Lahurabir, Varanasi",
        category=ReportCategory.roads,
        status=ReportStatus.improved,
        progress_percent=78,
        condition_score=8,
        description="Main road resurfacing is mostly complete and traffic movement has improved during peak hours.",
        evidence_url="https://example.com/varanasi-road-report",
        created_at=datetime(2026, 8, 22, tzinfo=timezone.utc),
        verified=True,
        verification_note="Evidence link and detailed citizen description present.",
    ),
    CitizenReport(
        id=2,
        politician_id=2,
        area="Kalpetta, Wayanad",
        category=ReportCategory.healthcare,
        status=ReportStatus.unchanged,
        progress_percent=45,
        condition_score=5,
        description="Primary health center wait times remain high, though medicine availability has slightly improved.",
        evidence_url=None,
        created_at=datetime(2026, 8, 24, tzinfo=timezone.utc),
        verified=False,
        verification_note="Pending moderator review.",
    ),
    CitizenReport(
        id=3,
        politician_id=3,
        area="Civil Lines, New Delhi",
        category=ReportCategory.education,
        status=ReportStatus.improved,
        progress_percent=86,
        condition_score=9,
        description="School classrooms were renovated and the new computer lab is operational for senior students.",
        evidence_url="https://example.com/delhi-school-update",
        created_at=datetime(2026, 8, 26, tzinfo=timezone.utc),
        verified=True,
        verification_note="Evidence link and detailed citizen description present.",
    ),
    CitizenReport(
        id=4,
        politician_id=6,
        area="Azamgarh city",
        category=ReportCategory.sanitation,
        status=ReportStatus.worsened,
        progress_percent=24,
        condition_score=3,
        description="Drain cleaning has not happened for weeks and waterlogging is recurring after short rainfall.",
        evidence_url="https://example.com/azamgarh-drainage",
        created_at=datetime(2026, 8, 28, tzinfo=timezone.utc),
        verified=True,
        verification_note="Evidence link and detailed citizen description present.",
    ),
]
